(function() {
  var simgen = require('./simgen.js'),
    baseAminoidData = require('./aminoids/base_aminoids'),



    aminoids = []
    orgDNA = simgen.create('DNA'),
    rnap = simgen.create('RNAPoly'),
    rnas = [],
    ribo = simgen.create('Ribosome'),
    polypeps = [];


  baseAminoidData.forEach(function(adata) {
    aminoids.push( simgen.create('Aminoid',adata) );
  });

  orgDNA.sequence(
    "ACGTACTGATCGTACGTAGCTAGCTGCAGCGAGATACGACTATCTGGACT" +
    "AGCACATATAAGACTACTGACTGATCTACGTACTAGCTACTGACTGACTG" +
    "TCAAGCATGCATACTGCAGTCTGACGCATACTGTAGCTGACTGTAGTGTG" +
    "TAGCTCATCTGTAGCTACTGTACTGACTGTACTGACTGACGGTCAGTACT" +
    "GACTGACGACTGACTGTACTGACTTACGTGAAAAAAAAAAAACTAGCGTA" +
    "TACTGCATACTGCATGACTGTACTCAGGACGGTATATATATAAATAATGC" +
    "GCGTACGTACGTGACTGCGCGATGCGCATGCAGTGCGCTCGCGCGCGCGG" +
    "GCGCGCGCGCGCGCGCATGATCTCAGTGCATGAGCTACTGCATGTACTGC" +
    "CTGAAAAAAAAAACTGTCGATGACTATGATCGATCGTACTGTACTGGGGG" +
    "GGGGGTATCGATTGGATGGATGGGGGGAAAAAGGGGGGGGGGGGGGACTG" +
    "TAGCTACGTCGGGGTACGTGCATGACTGTCAGTGACTGATGTAGCTGACT" +
    "TATGCATTATACTGTACGACTTACGTAGCTAGTATATAAAAGCATGCTTC" +
    "ACTGTCAGTGGCGGCTACGTCAGTCATGCATGTGACTGTGACGTATCGGG" +
    "TAGCGTACTGACGTCGTAGACGGACTGACTATCGACTGTGTACGTGACGC" +
    "AGCTACGTCGGGGTACGTGCAATGTCAGTCATGCATGTGACTGTCAGTCG" +
    "TACGTATGTATGACTAGTTAGCAGACGTGTACTGGTGCATGACGTGACGT" +
    "ACTGACGATGGACTGTACTGACTTACGTGAAAAAAAAAAAACTTTTATAG" +
    "TACTATGCGACTTACGTAGCATGTATATAAAAGCGACTTACGTAGCTAGT" +
    "TGCATACGTGCAGATTGGGGGGTATAATATTATAAAAGGTGACTTGTGAC" +
    "ACTGTACGACTGCGATTGGGGGGGGGCATGCAGTGCTACGTAGCGGGAAA" +
    "TACGACTTCTACGTCAGTTACGTGCATGACTCATGCCTACTGTACTGACT" +
    "TAGCTCATCTGTAGCTACTGTACTGACTGTACTGACTGACGGTCAGTACT" +
    "AGTCTGACGCATGATTGGGGGGTATTATGTATTTAAGGGACTGTAGCTGA" +
    "TAGCGTACTGTACGATTAAAAAAAAAAAAAAAAAATTACGTAGCACTGAC" +
    "TACGTGCATGGGCATGCAGTGACTTACGGCGGCTACGTCAGGTGCTGCCT" +
    "TAGCGTACTAGAGCGATTGGGGGGCATGCAGTCAGACGTGGCCGGACGAC" +
    "AGACGGAGCGCATGATTGGGGGGATGGCGACTTACGTAGCTACCCGTGCC"
  );

  rnas = rnap.transcribe(orgDNA);

  console.log('DNA:');
  console.log(orgDNA);

  console.log('RNAs:');
  console.log(rnas);


  rnas.forEach(function(rna) {
    polypeps.push( ribo.translate(rna) );
  });

  console.log('Polypeps:');
  console.log(polypeps);


})();