(function() {
  var DNA = require('./core/DNA'),
    RNA = require('./core/RNA'),
    Aminoid = require('./core/Aminoid'),
    RNAPoly = require('./core/RNAPoly'),
    Ribosome = require('./core/Ribosome'),

    baseAminoidData = require('./aminoids/base_aminoids'),



    aminoids = []
    orgDNA = new DNA(),
    rnap = new RNAPoly(),
    rnas = [],
    ribo = new Ribosome(),
    polypeps = [];


  baseAminoidData.forEach(function(adata) {
    aminoids.push(new Aminoid(adata));
  });

  orgDNA.sequence(
    "ACGTACTGATCGTACGTAGCTAGCTGCAGCGAGATACGACTATCTGGACT" +
    "AGCACATATAAGACTACTGACTGATCTACGTACTAGCTACTGACTGACTG" +
    "TCAAGCATGCATACTGCAGTCTGACGCATACTGTAGCTGACTGTAGTGTG" +
    "TAGCTCATCTGTAGCTACTGTACTGACTGTACTGACTGACGGTCAGTACT" +
    "GACTGACGACTGACTGTACTGACTTACGTGAAAAAAAAAAAACTAGCGTA" +
    "TACTGCATACTGCATGACTGTACTCAGGACGGTATATATATAAATAATGC" +
    "GCGTACGTACGTGACTGCGCGATGCGCATGCAGTGCGCTCGCGCGCGCGG" +
    "GCGCGCGCGCGCGCGCATGATCTCAGTGCATGAGCTACTGCATGTACTGC" +
    "CTGAAAAAAAAAACTGTCGATGACTATGATCGATCGTACTGTACTGGGGG" +
    "GGGGGTATCGATTGGATGGATGGGGGGAAAAAGGGGGGGGGGGGGGACTG" +
    "TAGCTACGTCGGGGTACGTGCATGACTGTCAGTGACTGATGTAGCTGACT" +
    "TATGCATTATACTGTACGACTTACGTAGCTAGTATATAAAAGCATGCTTC" +
    "ACTGTCAGTGGCGGCTACGTCAGTCATGCATGTGACTGTGACGTATCGGG" +
    "TAGCGTACTGACGTCGTAGACGGACTGACTATCGACTGTGTACGTGACGC" +
    "AGCTACGTCGGGGTACGTGCAATGTCAGTCATGCATGTGACTGTCAGTCG" +
    "TACGTATGTATGACTAGTTAGCAGACGTGTACTGGTGCATGACGTGACGT" +
    "ACTGACGATGGACTGTACTGACTTACGTGAAAAAAAAAAAACTTTTATAG" +
    "TACTATGCGACTTACGTAGCATGTATATAAAAGCGACTTACGTAGCTAGT" +
    "TGCATACGTGCAGATTGGGGGGTATAATATTATAAAAGGTGACTTGTGAC" +
    "ACTGTACGACTGCGATTGGGGGGGGGCATGCAGTGCTACGTAGCGGGAAA" +
    "TACGACTTCTACGTCAGTTACGTGCATGACTCATGCCTACTGTACTGACT" +
    "TAGCTCATCTGTAGCTACTGTACTGACTGTACTGACTGACGGTCAGTACT" +
    "AGTCTGACGCATGATTGGGGGGTATTATGTATTTAAGGGACTGTAGCTGA" +
    "TAGCGTACTGTACGATTAAAAAAAAAAAAAAAAAATTACGTAGCACTGAC" +
    "TACGTGCATGGGCATGCAGTGACTTACGGCGGCTACGTCAGGTGCTGCCT" +
    "TAGCGTACTAGAGCGATTGGGGGGCATGCAGTCAGACGTGGCCGGACGAC" +
    "AGACGGAGCGCATGATTGGGGGGATGGCGACTTACGTAGCTACCCGTGCC"
  );

  rnas = rnap.transcribe(orgDNA);

  console.log('RNAs:');
  console.log(rnas);


  rnas.forEach(function(rna) {
    polypeps.push( ribo.translate(rna) );
  });

  console.log('Polypeps:');
  console.log(polypeps);


})();